layout_spectrum: 0
color:
  saturation: 0.8951064
  lightness: 0.1810223
  brandStrength: 0.4758897
  rhythmicContrast: 0.5453098
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.8708627
name: Test BCS
