collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6364124
  brandStrength: 0
  lightness: 0.4279449
  brandColors:
    - '#010002'
    - '#626063'
    - '#878588'
    - '#DBD9DC'
    - '#BAB8BB'
  rhythmicContrast: 0.5269424
typography_spectrum: 0.5118152
layout_spectrum: 0.7011278
name: Brandon Carlos Scott
