color:
  saturation: 0.6364124
  brandStrength: 0
  rhythmicContrast: 0.5269424
  brandColors:
    - '#260000'
    - '#FCFFFF'
    - '#504F4D'
    - '#C29762'
    - '#BDBDC6'
  lightness: 0.4279449
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.7234157
typography_spectrum: 0.6407089
name: Brandon Carlos Scott
