collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.8708627
color:
  saturation: 0
  brandStrength: 0.4758897
  rhythmicContrast: 0
  lightness: 0
layout_spectrum: 0.2475832
name: Brandon Carlos Scott
